### ISSUE TITLE
Please update MIRACL submodule

### ISSUE THREAD

**Issue by lenerd** [encryptogroup/ENCRYPTO_utils#1]
Hi,
could you update the MIRACL submodule? Since miracl/MIRACL@c70e64e499bd054999b14058fc3f517d1c41ed9b it does not need custom patches anymore to compile MIRACL with Clang (cf. lenerd/MIRACL@edbc588c1cfb69cb55c0211b765dcaeb9e383d2e).

**Comment by lenerd** [comment]
Thank you very much!

**Comment by dd23** [comment]
done in e69521e72016a0a174054a1eab00d84140f16c43
I also updated this accordingly in OTExtension and ABY.
