### ISSUE TITLE
Detecting Machine Size

### ISSUE THREAD

**Issue by lenerd** [encryptogroup/ENCRYPTO_utils#10]
I am not convinced that this correctly identifies the processor's word size. The snipped seems to be copied from [here](https://lichess.org/forum/team-coders/fetching-the-machine-size-via-the-cc-preprocessor).

https://github.com/encryptogroup/ENCRYPTO_utils/blob/9f2fc807d86a37f986748955373d59fcc6c321d1/src/ENCRYPTO_utils/typedefs.h#L68-L75

The code below cannot distinguish between my x86-64 host system and a 32bit virtual machine. In both cases it outputs
```
MACHINE_SIZE_64
MAX_INT = ffffffff
```
I am not sure how this works.

```c++
#include <iostream>

int main()
{
#define MAX_INT (~0)
#if (MAX_INT == 0xFFFFFFFF)
#define MACHINE_SIZE_32
	std::cout << "MACHINE_SIZE_32\n";
#elif (MAX_INT == 0xFFFFFFFFFFFFFFFF)
#define MACHINE_SIZE_64
	std::cout << "MACHINE_SIZE_64\n";
#else
#define MACHINE_SIZE_16
	std::cout << "MACHINE_SIZE_16\n";
#endif

	std::cout << "MAX_INT = " << std::hex << MAX_INT << std::endl;
}
```

**Comment by dd23** [comment]
I just pushed f68596539cca5a68eb735f672fb1b3a13f8aff7c.
This commit removes the code from `typedefs.h` and changes the only place where this feature was used (in `cbitvector.cpp`) to check for `__WORDSIZE`.

If someone really wants to do this on ARM, we can add that later.
