### ISSUE TITLE
GMP Random Number Generator

### ISSUE THREAD

**Issue by lenerd** [encryptogroup/ENCRYPTO_utils#2]
Hi everyone,

I have noticed that the GMP random number generator is used in [`crypto/gmp-pk-crypto.cpp`](https://github.com/encryptogroup/ENCRYPTO_utils/blob/master/crypto/gmp-pk-crypto.cpp), [`crypto/dgk.cpp`](https://github.com/encryptogroup/ENCRYPTO_utils/blob/master/crypto/dgk.cpp) and [`crypto/djn.cpp`](https://github.com/encryptogroup/ENCRYPTO_utils/blob/master/crypto/djn.cpp).

It uses the Mersenne Twister as default (see [here](https://gmplib.org/manual/Random-State-Initialization.html#Random-State-Initialization)). Also, the random state is initialized with calls to [`rand`](https://linux.die.net/man/3/rand) (e.g. [here](https://github.com/encryptogroup/ENCRYPTO_utils/blob/master/crypto/dgk.cpp#L106)). Both random number generator are not suitable for cryptographic purposes.

**Comment by Oleksandr-Tkachenko** [comment]
Hi Lennart,

thank you so much for pointing this out! I replaced our PRNGs with /dev/urandom. This is a quick fix, and we will look more carefully into this issue soon. 

Best,
Alex
